Revert "style: clang-tidy"
This reverts commit aa84ff9d0cd2b31cda6e6b55b4f36cec7e61eec0.

not sure why..
```
src/session.cpp:105:19: error: no matching function for call to ‘std::__cxx11::basic_string<char>::erase(std::ranges::borrowed_subrange_t<std::__cxx11::basic_string<char>&>, std::__cxx11::basic_string<char>::iterator)’
  105 |         data.erase(std::ranges::remove(data, asciiEscape), data.end()); // don't accept ASCII code, might mess up terminal
      |         ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/session.cpp:105:19: note: there are 3 candidates
In file included from /usr/include/c++/15.1.1/string:56,
                 from /usr/include/c++/15.1.1/bits/locale_classes.h:42,
                 from /usr/include/c++/15.1.1/bits/ios_base.h:43,
                 from /usr/include/c++/15.1.1/ios:46,
                 from /usr/include/c++/15.1.1/bits/ostream.h:43,
                 from /usr/include/c++/15.1.1/bits/unique_ptr.h:43,
                 from /usr/include/c++/15.1.1/memory:80,
                 from src/chatManager.hpp:3,
                 from src/session.hpp:4,
                 from src/session.cpp:1:
/usr/include/c++/15.1.1/bits/basic_string.h:2323:7: note: candidate 1: ‘constexpr std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::erase(size_type, size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; size_type = long unsigned int]’
 2323 |       erase(size_type __pos = 0, size_type __n = npos)
      |       ^~~~~
/usr/include/c++/15.1.1/bits/basic_string.h:2323:23: note: no known conversion for argument 1 from ‘std::ranges::borrowed_subrange_t<std::__cxx11::basic_string<char>&>’ to ‘std::__cxx11::basic_string<char>::size_type’ {aka ‘long unsigned int’}
 2323 |       erase(size_type __pos = 0, size_type __n = npos)
      |             ~~~~~~~~~~^~~~~~~~~
/usr/include/c++/15.1.1/bits/basic_string.h:2343:7: note: candidate 2: ‘constexpr std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::iterator std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::erase(__const_iterator) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; iterator = std::__cxx11::basic_string<char>::iterator; __const_iterator = std::__cxx11::basic_string<char>::const_iterator]’
 2343 |       erase(__const_iterator __position)
      |       ^~~~~
/usr/include/c++/15.1.1/bits/basic_string.h:2343:7: note: candidate expects 1 argument, 2 provided
/usr/include/c++/15.1.1/bits/basic_string.h:2363:7: note: candidate 3: ‘constexpr std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::iterator std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::erase(__const_iterator, __const_iterator) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; iterator = std::__cxx11::basic_string<char>::iterator; __const_iterator = std::__cxx11::basic_string<char>::const_iterator]’
 2363 |       erase(__const_iterator __first, __const_iterator __last)
      |       ^~~~~
/usr/include/c++/15.1.1/bits/basic_string.h:2363:30: note: no known conversion for argument 1 from ‘std::ranges::borrowed_subrange_t<std::__cxx11::basic_string<char>&>’ to ‘std::__cxx11::basic_string<char>::__const_iterator’ {aka ‘std::__cxx11::basic_string<char>::const_iterator’}
 2363 |       erase(__const_iterator __first, __const_iterator __last)
      |             ~~~~~~~~~~~~~~~~~^~~~~~~
make: *** [Makefile:73: build/session.o] Error 1
make: *** Waiting for unfinished jobs....
```